(ns status-im.resources
  (:require [status-im.utils.modules :as modules]))

(def add-icon (modules/require-js "./images/add.png"))
(def att (modules/require-js "./images/att.png"))
(def chat-icon (modules/require-js "./images/chat.png"))
(def delivered-icon (modules/require-js "./images/delivered.png"))
(def delivery-failed-icon (modules/require-js "./images/deliveryfailed.png"))
(def icon-close-gray (modules/require-js "./images/icon_close_gray.png"))
(def leave-icon (modules/require-js "./images/leave.png"))
(def logo-icon (modules/require-js "./images/logo.png"))
(def mic (modules/require-js "./images/mic.png"))
(def nav-back-icon (modules/require-js "./images/nav-back.png"))
(def user-no-photo (modules/require-js "./images/no-photo.png"))
(def online-icon (modules/require-js "./images/online.png"))
(def play (modules/require-js "./images/play.png"))
(def seen-icon (modules/require-js "./images/seen.png"))
(def smile (modules/require-js "./images/smile.png"))
(def trash-icon (modules/require-js "./images/trash.png"))
(def v (modules/require-js "./images/v.png"))

(def contacts
  {:auction-house (modules/require-js "./images/contacts/auction-house.png")
   :mkr-market (modules/require-js "./images/contacts/mkr-market.png")
   :oaken-water-meter (modules/require-js "./images/contacts/oaken-water-meter.png")
   :flight-delays-suck (modules/require-js "./images/contacts/flight-delays-suck.png")
   :jarrad (modules/require-js "./images/contacts/jarrad.png")
   :firstblood (modules/require-js "./images/contacts/FirstBlood.png")
   :gnosis (modules/require-js "./images/contacts/gnosis.png")
   :melonport (modules/require-js "./images/contacts/melonport.png")
   :bchat (modules/require-js "./images/contacts/bchat.png")
   :dentacoin (modules/require-js "./images/contacts/Dentacoin.png")
   :augur (modules/require-js "./images/contacts/augur.png")
   :ethlance (modules/require-js "./images/contacts/ethlance.png")
   :commiteth (modules/require-js "./images/contacts/commiteth.png")
   :etherplay (modules/require-js "./images/contacts/etherplay.png")})
